version: 2.1

dependencies:
  cache_directories:
    - restaurants-api/node_modules
    - public-api/node_modules
    - db-backup/node_modules

orbs:
  node: circleci/node@1.1.6
jobs:
  build-public:
    working_directory: ~/public-api
    docker: # run the steps with Docker
      - image: circleci/node:10.16.3 # ...with this image as the primary container; this is where all `steps` will run
    steps:
      - checkout
      - run: cd public-api && npm install
      - run: cd public-api && npm test
      - run: cd public-api && ./node_modules/.bin/serverless deploy
            
  build-private:
    working_directory: ~/restaurants-api
    docker: # run the steps with Docker
      - image: circleci/node:10.16.3 # ...with this image as the primary container; this is where all `steps` will run
    steps:
      - checkout
      - run: cd restaurants-api && npm install
      - run: cd restaurants-api && npm test
      - run: cd restaurants-api && ./node_modules/.bin/serverless deploy

  build-backup:
    working_directory: ~/db-backup
    docker: # run the steps with Docker
      - image: circleci/node:10.16.3 # ...with this image as the primary container; this is where all `steps` will run
    steps:
      - checkout
      - run: cd db-backup && npm install
      - run: cd db-backup && ./node_modules/.bin/serverless deploy
            
workflows:
    build-test-deploy:
      jobs:
        - build-public:
          filters:
            branches:
              only: master
        - build-private:
          filters:
            branches:
              only: master
        - build-backup:
          filters:
            branches:
              only: master
