version: 2.1

dependencies:
  cache_directories:
    - private/node_modules
    - public/node_modules

orbs:
  node: circleci/node@1.1.6
jobs:
  build-public:
    working_directory: ~/public
    docker: # run the steps with Docker
      - image: circleci/node:10.16.3 # ...with this image as the primary container; this is where all `steps` will run
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: ./node_modules/.bin/serverless deploy
            
  build-private:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd private && npm install
            - run: cd private && npm test
            - run: cd private && ./node_modules/.bin/serverless deploy
workflows:
    build-test-deploy:
      jobs:
        - build-public:
          filters:
            branches:
              only: master
        - build-private:
          filters:
            branches:
              only: master
