version: 2.1

orbs:
  node: circleci/node@1.1.6
jobs:
  build-public:
    working_directory: './public'
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: ./node_modules/.bin/serverless deploy
  build-private:
    working_directory: './private'
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: ./node_modules/.bin/serverless deploy
workflows:
    build-test-deploy:
      jobs:
        - build-public:
          filters:
            branches:
              only: master
        - build-private:
          filters:
            branches:
              only: master
