version: 2.1

dependencies:
  cache_directories:
    - private/node_modules
    - public/node_modules

orbs:
  node: circleci/node@1.1.6
jobs:
  build-public:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd public && npm install
            - run: cd public && npm test
            - run: cd public && ./node_modules/.bin/serverless deploy
  build-private:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd private && npm install
            - run: cd private && npm test
            - run: cd private && ./node_modules/.bin/serverless deploy
workflows:
    build-test-deploy:
      jobs:
        - build-public:
          filters:
            branches:
              only: master
        - build-private:
          filters:
            branches:
              only: master
