version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-test-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: MONGO_QRY=${env.MONGO_QRY} MONGO_CONN=${env.MONGO_CONN} NODE_ENV=production ./node_modules/.bin/serverless deploy
workflows:
    build-test-deploy:
      jobs:
        - build-test-deploy:
          filters:
            branches:
              only: master
