service: restautant-platform-public

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs10.x

plugins:
  - serverless-offline
  - serverless-apigw-binary

custom:
  apigwBinary:
    types:
      - '*/*'

# The `functions` block defines what code to deploy
functions:
  api:
    handler: appServerless.handler
    events:
      - http: ANY /
        cors: true
      - http: 'ANY {proxy+}'
        cors: true
    environment:
      ENV_CONFIG: ${env:ENV_CONFIG}
      MONGO_QRY: ${env:MONGO_QRY}
      MONGO_CONN_STR: ${env:MONGO_CONN_STR}
